### ISSUE TITLE
Compatible with Redactor 2.0

### ISSUE THREAD

**Issue by PrimozRome** [itteco/redactor-oembed#5]
Hello

is this plugin compatible with new Redactor https://imperavi.com/redactor/ ?

Thanks

**Comment by iparamonau** [comment]
The plugin is compatible with v2.0 - the plugin demo runs on the latest version of Redactor. 

This said, there are couple issues remaining in Redactor 2.0 itself that keep it not embeds-friendly. The most inconvenient one is the backspace behaviour: when you edit text, some embed previews may get ruined due to CSS changes. The proper embed codes do get restored by our plugin before text is saved and sent to your database, but the user experience can be a little frustrating.
